[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hydentity = "46mwRQo4f6sLy9cigZdVJgdEpeEVc6jLRG1H241Uk9GY"

[programs.devnet]
hydentity = "7uBSpWjqTfoSNc45JRFTAiJ6agfNDZPPM48Scy987LDx"

[programs.mainnet]
hydentity = "7uBSpWjqTfoSNc45JRFTAiJ6agfNDZPPM48Scy987LDx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=b6fbdeee-e72d-49b9-92bc-d607d85be5bf"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
